# Generated by Django 5.2.17 on 2026-08-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='test_cases',
            field=models.JSONField(default=list),
        ),
    ]
