# Generated by Django 5.2.17 on 2026-08-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('problems_per_day', models.IntegerField(default=2)),
                ('roadmap_data', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
